da:
  messages:
    notification:
      free_trial: 'You are currently using the free trial'
  button:
    upgrade_plan: 'Upgrade Now'
    logout: 'Logout'
  top_menu:
    quick_search: 'Quick search...'
    users_block:
      profile: 'Profile'
      edit: 'edit'
      settings: 'Settings'
      contact_support: 'Contact Support'
  sidebar_menu:
    dashboard: 'Dashboard'
    sales: 'Sales'
    events: 'Events'
    crm: 'CRM'
    servicing: 'Servicing'
    reports: 'Reports'
  sales_submenu:
    point_of_sale: 'Point-of-Sale'
    sales_history: 'Sales History'
    products: 'Products'
    brands: 'Brands'
    categories: 'Categories'
    gift_cards: 'Gift Cards'
    credit_notes: 'Credit Notes'
    sales_targets: 'Sales Targets'
    event_tariffs: 'Event Tariffs'
  events_submenu:
    calendar: 'Calendar'
    list: 'List'
  crm_submenu:
    customers: 'Customers'
    suppliers: 'Suppliers'
    staff: 'Staff'
  servicing_submenu:
    all_services: 'All Services'
    booked: 'Booked'
    in_progress: 'In Progress'
    to_collect: 'To Collect'
    complete: 'Complete'
  reports_submenu:
      sales_by_time: 'Sales by Time'
      sales_by_staff: 'Sales by Staff'
      sales_by_brand: 'Sales by Brand'
      sales_by_category: 'Sales by Category'
      popular_products: 'Popular Products'
      event_sales: 'Event Sales'
      finance_reports: 'Finance Reports'
